---
title: "MDP Trabajo Clustering"
author: "Isabelle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r librerias clustering}
library(knitr)
library(cluster)
library(FactoMineR)
library(factoextra)
library(NbClust)
library(clValid)
```
# RATONES

## Datos y descripci칩n

```{r datos}

datos = read_excel("RatonesLimpios.xlsx", col_names = TRUE)
datos = as.data.frame(datos)

newID = sapply(datos$MouseID, function (x) strsplit(x, "_")[[1]][1])
head(datos, 3)
```

```{r}
descRatones = data.frame("variable" = colnames(datos),
                      "tipo" = c("categorical", rep("numerical", 75),
                                 rep("binary", 3), "categorical"), stringsAsFactors = FALSE)
rownames(descRatones) = descRatones$variable
descRatones
```

# Centrar los datos

```{r centrar}

# Apply centering ONLY to the final list of numeric columns
datos[,2:76] <- scale(datos[,2:76], center = TRUE, scale = FALSE)

# View first 3 rows
head(datos, 3)

```

## Selecci칩n de variables a utilizar y preparaci칩n de datos


```{r}
datos_num = datos[,descRatones$variable[descRatones$tipo == "numerical"]]
head(datos_num)
```


## Medida de distancia y tendencia de agrupamiento
```{r dist}
midist <- get_dist(datos, stand = FALSE, method = "euclidean")
fviz_dist(midist, show_labels = TRUE, lab_size = 0.3,
          gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r hopkins}
set.seed(100)
myN = c(20, 35, 50, 65)  # m
myhopkins = NULL
myseed = sample(1:1000, 10)
for (i in myN) {
  for (j in myseed) {
    tmp = get_clust_tendency(data = datos_num, n = i, graph = FALSE, seed = j)
    myhopkins = c(myhopkins, tmp$hopkins_stat)
  }
}
summary(myhopkins)
```

## Modelos jer치rquicos
