---
title: "MDP_Proyecto"
author: "Nadal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r carga}
# Cargar paquetes necesarios
library(ggplot2)
library(ggfortify)
library(dplyr)
library(tidyr)
library(factoextra)
library(readxl)
```

```{r lectura_df}
#Leer datos del .xlsx
df = read_excel("Data_Cortex_Nuclear.xlsx")
```

```{r faltantes}
# 1. Análisis de valores faltantes
missing_by_variable <- colSums(is.na(df))  # Valores faltantes por variable
missing_by_individual <- rowSums(is.na(df)) # Valores faltantes por individuo

# Resumen de valores faltantes
print("Valores faltantes por variable:")
print(missing_by_variable)
print("Valores faltantes por individuo:")
print(missing_by_individual)

```

```{r analisis_variacion}
# 2. Análisis de variación por variable
variation_by_variable <- apply(df[, sapply(df, is.numeric)], 2, var, na.rm = TRUE)
print("Variación por variable:")
print(variation_by_variable)

```


```{r PCA}
# 3. Análisis PCA
numeric_df <- df[, sapply(df, is.numeric)]  # Seleccionar solo columnas numéricas
numeric_df <- na.omit(numeric_df)  # Eliminar filas con valores faltantes

pca_result <- prcomp(numeric_df, center = TRUE, scale. = TRUE)  # Realizar PCA

# Gráfico de cargas (loadings plot)
fviz_pca_var(pca_result, col.var = "cos2", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

```





